import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Header from "@/features/header/components/Header";
import ScrollToTopButton from "@/features/scroll-to-top-button/components/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme radius="medium">
          <Header />
          <main>{children}</main>
          <ScrollToTopButton />
          <footer className="h-72 bg-neutral-dark"></footer>
        </Theme>
      </body>
    </html>
  );
}
